Minor updates to the development instructions.
glotzerlab/signac pull request #216
Opened 2019-08-08 22:21 UTC by csadorf

1. Make conda recommended method for environment management.
2. Make commands copy & pastable by removing the prompt.
3. Enumerate instructions.

2019-08-09 14:18 UTC, vyasr approved these changes
Approving pending the one fix.

2019-08-09 14:20 UTC, csadorf commented on doc/support.rst
> +    source ~/envs/signac-flow-dev/bin/activate
Thx for the catch!

2019-08-09 18:39 UTC, b-butler requested changes
Everything besides the conda part is good.

2019-08-09 18:39 UTC, b-butler commented on doc/support.rst
> +    conda create -n signac-dev python --file requirements-dev.txt
This will not work and just just be `conda create -n signac-dev python`

2019-08-09 18:39 UTC, b-butler commented on doc/support.rst
> +    conda activate signac-dev
We should give follow up comments regarding how to properly set up the environment.

2019-08-12 15:49 UTC, csadorf commented
Let's just leave it *as-is* for now.

2019-08-12 15:49 UTC, closed without merging