Deprecate copytree method
glotzerlab/signac pull request #439
Opened 2020-12-19 20:58 UTC by shandave

## Description

Deprecate copytree method
## Motivation and Context

Resolves #432 

## Types of Changes

- [ ] Documentation update
- [ ] Bug fix
- [ ] New feature
- [ ] Breaking change<sup>1</sup>

<sup>1</sup>The change breaks (or has the potential to break) existing functionality.

## Checklist:

- [x] I am familiar with the [**Contributing Guidelines**](https://github.com/glotzerlab/signac/blob/master/CONTRIBUTING.md).
- [x] I agree with the terms of the [**Contributor Agreement**](https://github.com/glotzerlab/signac/blob/master/ContributorAgreement.md).
- [ ] My name is on the [list of contributors](https://github.com/glotzerlab/signac/blob/master/contributors.yaml).
- [x] My code follows the [code style guideline](https://github.com/glotzerlab/signac/blob/master/CONTRIBUTING.md#code-style) of this project.
- [ ] The changes introduced by this pull request are covered by existing or newly introduced tests.

If necessary:
- [ ] I have updated the API documentation as part of the package doc-strings.
- [ ] I have created a separate pull request to update the [framework documentation](https://docs.signac.io/) on [signac-docs](https://github.com/glotzerlab/signac-docs) and linked it here.
- [ ] I have updated the [changelog](https://github.com/glotzerlab/signac/blob/master/changelog.txt) and added all related issue and pull request numbers for future reference (if applicable). See example below.

2020-12-19 21:00 UTC, shandave commented
@bdice I deprecated the copytree method, but I'm not sure how to perform step 3 mentioned in your proposed solution.

2020-12-19 21:07 UTC, bdice commented
> @bdice I deprecated the copytree method, but I'm not sure how to perform step 3 mentioned in your proposed solution.

@shandave Thank you for the pull request! Step 3 is basically just a “find and replace” operation. Anywhere that the code says `syncutil.copytree` should be changed to `shutil.copytree`. We appreciate your contribution!

2020-12-19 23:28 UTC, bdice commented on signac/syncutil.py
> +    removed_in="2.3.0",
We'll remove this in the next major release, 2.0.0. 👍
```suggestion
    removed_in="2.0.0",
```

2020-12-28 22:19 UTC, b-butler requested changes
@shandave I noticed there are a couple of references to `syncutil.copytree` remaining in `signac/contrib/project.py` lines 1439 and 1451.

2021-01-13 04:18 UTC, bdice commented
@shandave I noticed you pushed a commit. Please tag the assigned reviewers in a comment when you're ready for someone to review again. Please add a note to the changelog and add yourself to the contributors list as you did for signac-flow. Thank you again! 😄

2021-01-13 04:45 UTC, shandave commented
Thank You @bdice , @b-butler and @cbkerr for reviewing my commit and suggesting the changes; I would like to review my commit again, I have made all the changes suggested in the comment.

2021-01-13 15:26 UTC, b-butler commented
@shandave I still see multiple uses of `syncutil.copytree` in `signac/contrib/project.py`. In the `clone` method of the `Project` class. This should default to `shutil.copytree` now.

2021-01-13 16:48 UTC, shandave commented
Thank You @b-butler for reviewing. I have made the suggested changes.

2021-01-13 17:30 UTC, bdice commented
@shandave Tests are failing:
```
signac/contrib/project.py:25:1: F401 '..syncutil' imported but unused
signac/contrib/project.py:1497:35: F821 undefined name 'shutil'
```
You need to remove the import of `syncutil` and add `import shutil`. You should install pre-commit with these instructions to catch problems like these: https://docs.signac.io/projects/core/en/latest/support.html#set-up-a-development-environment

Also please update the changelog and contributors list.

2021-01-13 18:24 UTC, shandave commented
Thank You @bdice for giving me an opportunity to contribute in signac. I have made the suggested changes. Thank you again for helping me out.

2021-01-13 19:44 UTC, bdice approved these changes
Great work @shandave! Thanks for your persistence. I have two small changes to apply. I will go ahead and make those changes, and approve this PR. Once a second reviewer approves the PR, we will merge it.

2021-01-13 19:44 UTC, bdice commented on signac/contrib/project.py
> +             (Default value = shutil.copytree)
This will appear with a link in the documentation.
```suggestion
             (Default value = :func:`shutil.copytree`)
```

2021-01-13 19:44 UTC, bdice commented on contributors.yaml
> +  -
Remove extra dash.
```suggestion
```

2021-01-21 20:36 UTC, b-butler approved these changes
LGTM

2021-01-21 20:59 UTC, merged