Check up on restrictions to signac view
glotzerlab/signac pull request #926
Opened 2023-05-29 16:03 UTC by cbkerr

## Description

I had a space in my state point and was surprised that I couldn't make a signac view. This fix worked for me on mac but I'll run the tests on Windows and Linux through GitHub.

## Motivation and Context

The PR that created this restriction was initially a fix involving path separation characters but there was [no reason given for also excluding spaces and asterisks](https://github.com/glotzerlab/signac/pull/233#issuecomment-547587695). I was able to create views in tests with these characters on mac.

I tested this locally with my project that had spaces in the state point after this change, and it worked.

There are [other characters we might want to exclude as well](https://www.informit.com/articles/article.aspx?p=1144082&seqNum=5), like `?`, `[]`, `{}`. These characters might be annoying to escape on the terminal, but a strong use of view is to browse in a file browser.

Perhaps we can emit a warning about special characters being used?

I think if the tests pass in creating views, then we should be good to create views with spaces and asterisks in the state point.

## Checklist:

- [x] I am familiar with the [Contributing Guidelines](https://github.com/glotzerlab/signac/blob/main/CONTRIBUTING.md).
- [x] I agree with the terms of the [Contributor Agreement](https://github.com/glotzerlab/signac/blob/main/ContributorAgreement.md).
- [x] My name is on the [list of contributors](https://github.com/glotzerlab/signac/blob/main/contributors.yaml).
- [x] The changes introduced by this pull request are covered by existing or newly introduced tests.
- [ ] The [package documentation](https://github.com/glotzerlab/signac/tree/main/doc) and [framework documentation](https://docs.signac.io/) in [signac-docs](https://github.com/glotzerlab/signac-docs) are up to date with these changes.
- [ ] I have updated the [changelog](https://github.com/glotzerlab/signac/blob/main/changelog.txt) and added any related issue and pull request numbers for future reference.

2023-05-31 18:26 UTC, b-butler requested changes
Just a couple of quick changes.

2023-05-31 18:26 UTC, b-butler commented on signac/linked_view.py
> +    bad_chars = [os.sep]
We don't need a list any more. It should also be a quicker check to use `==`.

2023-06-03 00:21 UTC, vyasr commented
Spaces were probably excluded because they don't work on older filesystems, and I'm guessing that one of the supercomputers we originally cared about (maybe the original Stampede, not even Stampede2? Not sure) was an example. I'm fine with removing the restriction and leaving the onus on the user to recognize why a view fails if they have such a filesystem.

2023-07-12 16:20 UTC, bdice commented
@cbkerr @b-butler Can you push this through?

2023-07-19 17:41 UTC, b-butler approved these changes

2023-07-19 17:42 UTC, merged